/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package landlord;

/**
 *
 * @author corpu
 */
public class cardroom extends javax.swing.JPanel {
    String r_id;
    managerooms parentFrame;

    /**
     * Creates new form cardroom
     */
    public cardroom(String id, String name, String type, String price, String location, String desc, String status, managerooms parent) {
        initComponents();
        this.r_id = id;
        this.parentFrame = parent;
        roomname.setText(name);
        roomtype.setText(type);
        roomprice.setText("₱" + price);
        roomlocation.setText(location);
        description.setText(desc); // Ensure this label is wide enough for text
        roomstatus.setText(status);
    
    // Status color logic
    if(status.equalsIgnoreCase("Available")){
        roomstatus.setForeground(new java.awt.Color(0, 153, 0)); // Dark Green
    } else {
        roomstatus.setForeground(java.awt.Color.RED);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        roomstatus = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        roomname = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        remove = new javax.swing.JButton();
        roomtype = new javax.swing.JLabel();
        roomprice = new javax.swing.JLabel();
        roomlocation = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel33.setText("Status:");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        roomstatus.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel3.add(roomstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 210, 20));

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        edit.setText("Edit");
        edit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 130, 30));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel23.setText("Room Name:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        roomname.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel3.add(roomname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 150, 20));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel29.setText("Price:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 40, -1));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel30.setText("Room Type:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel31.setText("Location:");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel32.setText("Description:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        remove.setBackground(new java.awt.Color(255, 255, 255));
        remove.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        remove.setText("Remove");
        remove.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel3.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 130, 30));

        roomtype.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel3.add(roomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 210, 20));

        roomprice.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel3.add(roomprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 210, 20));

        roomlocation.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel3.add(roomlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 210, 20));

        description.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel3.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 210, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/web/images/backgroundr.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    editroom ed = new editroom(r_id, roomname.getText(), roomtype.getText(), 
                               roomprice.getText().replace("₱", ""), // Remove peso sign for editing
                               roomlocation.getText(), description.getText(), parentFrame);
    ed.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
    int confirm = javax.swing.JOptionPane.showConfirmDialog(null, 
            "Are you sure you want to delete " + roomname.getText() + "?", 
            "Delete Room", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // 1. Create the Config object
        Config.config con = new Config.config();
        
        // 2. Use the SQL with a '?' placeholder (safer)
        String sql = "DELETE FROM rooms WHERE r_id = ?";
        
        // 3. Use the method that worked before: updateRecord(sql, value)
        con.updateRecord(sql, r_id); 
        
        // 4. Show success and refresh the parent frame
        javax.swing.JOptionPane.showMessageDialog(null, "Room Successfully Deleted");
        
        if (parentFrame != null) {
            parentFrame.loadRooms();
        }
    }// TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton remove;
    private javax.swing.JLabel roomlocation;
    private javax.swing.JLabel roomname;
    private javax.swing.JLabel roomprice;
    private javax.swing.JLabel roomstatus;
    private javax.swing.JLabel roomtype;
    // End of variables declaration//GEN-END:variables
}
