/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tenant;

/**
 *
 * @author corpu
 */
public class roomcard extends javax.swing.JPanel {
    private int currentRoomId;
    private int currentLandlordId;

    /**
     * Creates new form roomcard
     */
   public roomcard(int rId, int lId, String rName, String rType, String rPrice, String rLocation, String rDesc) {
      
        initComponents(); 
        
        // FIX: You MUST assign the parameters to your class variables here
        this.currentRoomId = rId;
        this.currentLandlordId = lId;
    
        // Set your labels
        name.setText(rName);
        type.setText(rType);
        price.setText(rPrice);
        location.setText(rLocation);
        description.setText(rDesc);
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        reserve = new javax.swing.JButton();
        type = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel23.setText("Room Name:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 150, 20));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel29.setText("Price:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 40, -1));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel30.setText("Room Type:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel31.setText("Location:");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel32.setText("Description:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        reserve.setBackground(new java.awt.Color(255, 255, 255));
        reserve.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        reserve.setText("Reserve Room");
        reserve.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveActionPerformed(evt);
            }
        });
        jPanel3.add(reserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 130, 30));
        jPanel3.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 210, 20));
        jPanel3.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 210, 20));
        jPanel3.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 210, 20));
        jPanel3.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 210, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/web/images/backgroundr.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 160));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveActionPerformed
    tenantreserve tr = new tenantreserve(currentRoomId, currentLandlordId, name.getText());
    tr.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_reserveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel location;
    private javax.swing.JLabel name;
    private javax.swing.JLabel price;
    private javax.swing.JButton reserve;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
