/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import Config.config;

/**
 *
 * @author corpu
 */
public class addres extends javax.swing.JFrame {
    private reservations parentFrame;

    /**
     * Creates new form addres
     */
    public addres() {
        initComponents();
        loadAutoFillData();
    }

    public addres(reservations parent) {
        initComponents();
        this.parentFrame = parent;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (parentFrame != null) {
                    parentFrame.setVisible(true);
                }
            }
        });
        loadAutoFillData();
    }

    private void loadAutoFillData() {
        resid.setText("(Auto-generated)");
        try (Connection conn = config.connectDB()) {
            ResultSet rs = conn.createStatement().executeQuery("SELECT COALESCE(MAX(res_id), 0) + 1 AS next_id FROM reservations");
            if (rs.next()) {
                resid.setText(String.valueOf(rs.getInt("next_id")));
            }
        } catch (SQLException e) {
            resid.setText("Auto");
        }
        DefaultComboBoxModel<String> roomModel = new DefaultComboBoxModel<>();
        roomModel.addElement("-- Select Room --");
        DefaultComboBoxModel<String> userModel = new DefaultComboBoxModel<>();
        userModel.addElement("-- Select User --");
        try (Connection conn = config.connectDB()) {
            ResultSet rs = conn.createStatement().executeQuery("SELECT r_id, r_name FROM rooms ORDER BY r_id");
            while (rs.next()) {
                roomModel.addElement(rs.getInt("r_id") + " - " + rs.getString("r_name"));
            }
            rs = conn.createStatement().executeQuery("SELECT id, username FROM users ORDER BY id");
            while (rs.next()) {
                userModel.addElement(rs.getInt("id") + " - " + rs.getString("username"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading rooms/users: " + e.getMessage());
        }
        roomid1.setModel(roomModel);
        userid.setModel(userModel);
        if (roomModel.getSize() > 1) {
            roomid1.setSelectedIndex(1);
        }
        if (userModel.getSize() > 1) {
            userid.setSelectedIndex(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        moveindate = new javax.swing.JTextField();
        contract = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        resid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        userid = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        roomid1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 260, 40));

        moveindate.setBorder(null);
        moveindate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveindateActionPerformed(evt);
            }
        });
        jPanel2.add(moveindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 260, 30));

        contract.setBorder(null);
        contract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractActionPerformed(evt);
            }
        });
        jPanel2.add(contract, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 260, 30));

        contact.setBorder(null);
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 260, 30));

        status.setBorder(null);
        jPanel2.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 260, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User ID ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 20));

        resid.setEditable(false);
        resid.setBorder(null);
        resid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residActionPerformed(evt);
            }
        });
        jPanel2.add(resid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 260, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel12.setText("Reservations Form");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 40));

        userid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 260, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 20));

        roomid1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(roomid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 260, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Move-in Date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contract");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, 20));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Room ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reservation ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/web/images/crud.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        Object roomSel = roomid1.getSelectedItem();
        Object userSel = userid.getSelectedItem();
        if (roomSel == null || roomSel.toString().startsWith("--") || userSel == null || userSel.toString().startsWith("--")
                || contact.getText().trim().isEmpty() || moveindate.getText().trim().isEmpty() || status.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select Room and User, and fill in all required fields.");
            return;
        }
        try {
            int roomId = Integer.parseInt(roomSel.toString().split(" - ")[0]);
            int userId = Integer.parseInt(userSel.toString().split(" - ")[0]);
            int adminId = config.Session.getInstance().getUid();
            Connection conn = config.connectDB();
            String sql = "INSERT INTO reservations (id, r_id, contact, move_in_date, contract, status, admin_id) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, userId);
            pst.setInt(2, roomId);
            pst.setString(3, contact.getText().trim());
            pst.setString(4, moveindate.getText().trim());
            pst.setString(5, contract.getText().trim());
            pst.setString(6, status.getText().trim());
            pst.setInt(7, adminId);
            pst.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(this, "Reservation saved successfully.");
            if (parentFrame != null) {
                parentFrame.displayAllReservations();
                parentFrame.setVisible(true);
            } else {
                new reservations().setVisible(true);
            }
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for User ID and Room ID.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saving reservation: " + e.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void moveindateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveindateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveindateActionPerformed

    private void contractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contractActionPerformed

    private void residActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact;
    private javax.swing.JTextField contract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField moveindate;
    private javax.swing.JTextField resid;
    private javax.swing.JComboBox<String> roomid1;
    private javax.swing.JButton save;
    private javax.swing.JTextField status;
    private javax.swing.JComboBox<String> userid;
    // End of variables declaration//GEN-END:variables
}
