/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import Config.config;

/**
 *
 * @author corpu
 */
public class editroom extends javax.swing.JFrame {
    private byte[] roomImageBytes;
    private String roomID;
    private rooms parentFrame;

    /**
     * Creates new form editroom
     */
    public editroom() {
        initComponents();
    }

    public editroom(String rId, rooms parent) {
        initComponents();
        this.roomID = rId;
        this.parentFrame = parent;
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (parentFrame != null) {
                    parentFrame.setVisible(true);
                } else {
                    new rooms().setVisible(true);
                }
                dispose();
            }
        });
        loadDetails();
    }

    private void loadDetails() {
        try (Connection conn = config.connectDB()) {
            String sql = "SELECT * FROM rooms WHERE r_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, roomID);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                roomname.setText(rs.getString("r_name"));
                type.setText(rs.getString("r_type"));
                price.setText(rs.getString("r_price"));
                location.setText(rs.getString("r_location"));
                description.setText(rs.getString("r_description"));
                try {
                    status.setText(rs.getString("r_status"));
                } catch (SQLException ignored) { /* r_status column may not exist */ }

                try {
                    roomImageBytes = rs.getBytes("r_image");
                    if (roomImageBytes != null) {
                        ImageIcon icon = new ImageIcon(roomImageBytes);
                        
                        int width = roomimageselector.getWidth();
                        int height = roomimageselector.getHeight();
                        if (width == 0 || height == 0) {
                            width = 260;
                            height = 150;
                        }
                        
                        Image img = icon.getImage();
                        Image scaled = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                        roomimageselector.setIcon(new ImageIcon(scaled));
                    }
                } catch (SQLException ignored) { /* r_image column may not exist */ }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading room: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        select = new javax.swing.JButton();
        save = new javax.swing.JButton();
        roomname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        roomimageselector = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        select.setBackground(new java.awt.Color(255, 255, 255));
        select.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel2.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 260, 40));

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        save.setText("Update");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 260, 40));

        roomname.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        roomname.setBorder(null);
        jPanel2.add(roomname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 260, 30));

        price.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        price.setBorder(null);
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 260, 30));

        location.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        location.setBorder(null);
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });
        jPanel2.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 260, 30));

        type.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        type.setBorder(null);
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 260, 30));

        description.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        description.setBorder(null);
        jPanel2.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 260, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Status");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 20));

        status.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        status.setBorder(null);
        jPanel2.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 260, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel12.setText("Rooms Form");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Room Type");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Location");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 20));

        roomimageselector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/web/images/addimage.png"))); // NOI18N
        jPanel2.add(roomimageselector, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 260, 150));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Description");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/web/images/crud.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                roomImageBytes = Files.readAllBytes(file.toPath());
                ImageIcon icon = new ImageIcon(roomImageBytes);
                
                int width = roomimageselector.getWidth();
                int height = roomimageselector.getHeight();
                if (width == 0 || height == 0) {
                    width = 260;
                    height = 150;
                }
                
                Image img = icon.getImage();
                Image scaled = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                roomimageselector.setIcon(new ImageIcon(scaled));
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Failed to load image: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_selectActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if (roomID == null) {
            JOptionPane.showMessageDialog(this, "No room loaded.");
            return;
        }

        String name = roomname.getText().trim();
        String priceText = price.getText().trim();
        String typeText = type.getText().trim();
        String locationText = location.getText().trim();
        String descText = description.getText().trim();
        String statusText = status.getText().trim();

        if (name.isEmpty() || priceText.isEmpty() || typeText.isEmpty() || locationText.isEmpty() || descText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
            return;
        }

        try {
            double priceVal = Double.parseDouble(priceText);
            Connection conn = config.connectDB();
            String sql = "UPDATE rooms SET r_name = ?, r_type = ?, r_price = ?, r_location = ?, r_description = ? WHERE r_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, name);
            pst.setString(2, typeText);
            pst.setDouble(3, priceVal);
            pst.setString(4, locationText);
            pst.setString(5, descText);
            pst.setString(6, roomID);
            pst.executeUpdate();
            
            try {
                PreparedStatement pst2 = conn.prepareStatement("UPDATE rooms SET r_status = ? WHERE r_id = ?");
                pst2.setString(1, statusText.isEmpty() ? "Available" : statusText);
                pst2.setString(2, roomID);
                pst2.executeUpdate();
            } catch (SQLException ignored) { /* r_status column may not exist */ }

            if (roomImageBytes != null) {
                try {
                    PreparedStatement pst3 = conn.prepareStatement("UPDATE rooms SET r_image = ? WHERE r_id = ?");
                    pst3.setBytes(1, roomImageBytes);
                    pst3.setString(2, roomID);
                    pst3.executeUpdate();
                } catch (SQLException ignored) { /* r_image column may not exist */ }
            }

            conn.close();
            JOptionPane.showMessageDialog(this, "Room updated successfully.");
            if (parentFrame != null) {
                parentFrame.displayAllRooms();
                parentFrame.setVisible(true);
            } else {
                new rooms().setVisible(true);
            }
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for Price.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error updating room: " + e.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField location;
    private javax.swing.JTextField price;
    private javax.swing.JLabel roomimageselector;
    private javax.swing.JTextField roomname;
    private javax.swing.JButton save;
    private javax.swing.JButton select;
    private javax.swing.JTextField status;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
